# Given a semver (major.minor.patch) strategy, this action increments the minor version
# for each push to main. If the commit log contains the string #patch, it will increment
# the patch version. If it contains the string #major, it will increment the major version.
#
# Versions are identified as git tags. A tag push invokes a jenkins build, and the
# jgitver maven extension produces artifacts based on the current tag value.
#
name: Bump version
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
      ref: my-branch
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        REPO_OWNER: aboveproperty
