# Given a semver (major.minor.patch) strategy, this action increments the minor version
# for each push to main. If the commit log contains the string #patch, it will increment
# the patch version. If it contains the string #major, it will increment the major version.
#
# Versions are identified as git tags. A tag push invokes a jenkins build, and the
# jgitver maven extension produces artifacts based on the current tag value.
#
name: release
on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          ref: main
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: aboveproperty

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Deploy to GitHub
        run: mvn --no-transfer-progress -DuseGitHubPackages=true clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine the released version
        run: echo "RELEASED_VERSION="$(mvn --no-transfer-progress help:evaluate -Dexpression=jgitver.used_version -q -DforceStdout) >> $GITHUB_ENV

      - name: Build github release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            LICENSE.txt
            target/*.jar

      - name: Notify slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: "${{ job.status == 'success' && 'good' || 'danger' }}"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: build
          SLACK_USERNAME: Bob the Builder
          SLACK_ICON: 'https://www.clipartmax.com/png/middle/416-4161958_bob-the-builder-transparent-transparent-background-bob-the-builder-png.png'
          SLACK_FOOTER: '${{ github.repository }}'
          SLACK_TITLE: 'Above Property ci-demo Release'
          SLACK_MESSAGE: ${{ env.RELEASED_VERSION }}

